### PR TITLE
Add Cosmos blog section

### PR DESCRIPTION
**Pull request by deniseyu**
Jekyll has some strong opinions about the `posts` collection so I think the easiest way to do this without messing up the existing Dripline content or introducing any changes to the Dripline workflow, is to set up the Cosmos blog as a new `collection`.

To do:

- [x] Add real content
- [x] Verify that cosmos index page is styled correctly after actual content
- [x] Verify that date ordering working as expected
- [x] Figure out why the `scope` config for default layout isn't working

### CODE REVIEW

**Comment by tripledoublev** [comment]
I changed the base branch to staging

**Comment by deniseyu** [comment]
I'm not sure why CI is breaking - is it because the page hasn't been built yet in prod? Will that go away on its own after being merged into main?

**Comment by tripledoublev** [comment]
I think it was simply a matter of adding a trailing slash. Let's see how the check goes

**Review by tripledoublev — APPROVED** [review]
Looks good!

**Pull request merged**
