### PR TITLE
news dripline post ready to go

### PR DESCRIPTION
**Pull request by writerly03**
pushing this to staging... or trying!

### CODE REVIEW

**Comment by writerly03** [comment]
@ASoTNetworks does this work to check the post on staging?

**Comment by ASoTNetworks** [comment]
> @ASoTNetworks does this work to check the post on staging?

Yep that will work and we can merge it into staging. After that we change directly in the staging branch and PR into master from staging branch once ready for public viewing.

**Comment by benhylau** [comment]
I think once this is verified on https://staging.hypha.coop/dripline/ we can merge this PR and make sure not to delete `staging`. Then we close #68 as that's not needed anymore.

**Comment by writerly03** [comment]
> 

Confirmed that the post looks good on staging. Can we proceed to the next step? LMK if I need to do anything on my end

**Pull request merged**
