### PR TITLE
Adding email to header, reorder Work with us

### LINKED ISSUE #3: Move "work with us" to bottom of page
Preference indicated in chat for "Work with us" to be at the bottom of the page: 
https://matrix.to/#/!wvFLvXHaNrxWWwFOKj:tomesh.net/$1585950106812ThfuC:tomesh.net?via=tomesh.net&via=elon.li

### LINKED ISSUE #4: Add some form of contact info "above the fold"
The CTA with our contact info appears about mid-way down the page (tho there is some interest in moving it to the bottom for flow of text (see #1 and #3). 

In chat this has been discussed: https://matrix.to/#/!wvFLvXHaNrxWWwFOKj:tomesh.net/$1585951376825YhGIu:tomesh.net?via=tomesh.net&via=elon.li with soft support

### PR DESCRIPTION
**Pull request by garrying**
- Closes #4
- Closes #3

### CODE REVIEW

**Review by dcwalk — APPROVED** [review]
I'm fine with this, but don't love it (the  [at] hypha [dot] coop feels totally unnecessary to me and not required stylistically, would be slightly into hello@hypha.coop more)

**Comment by dcwalk** [comment]
Should we also address #3 at the same time?

**Comment by uditvira** [comment]
> I'm fine with this, but don't love it (the [at] hypha [dot] coop feels totally unnecessary to me and not required stylistically, would be slightly into [hello@hypha.coop](mailto:hello@hypha.coop) more)

I may have introduced in the deck, but also feeling [hello@hypha.coop](mailto:hello@hypha.coop) more.

**Comment by garrying** [comment]
Updated email and order of "Work with us" in 9d870ad

**Pull request merged**
