### PR TITLE
news dripline post ready to go

### PR DESCRIPTION
**Pull request by writerly03**
Mauve's latest p2p post is ready to go. Can one of you review it? Do I need to do anything after that or does the PR publish the page and it's live?

### CODE REVIEW

**Comment by ASoTNetworks** [comment]
wonder if this should be PR into staging first since merging to master will update the live page without review

**Comment by writerly03** [comment]
> wonder if this should be PR into staging first since merging to master will update the live page without review

@ASoTNetworks yes, probably. I'm just not clear on how to do that. I have reviewed the page locally, but I thought the process was staging before live?

**Comment by ASoTNetworks** [comment]
If you PR into the staging branch and merged it will show up on https://staging.hypha.coop/ that way anyone can review the content without deploying locally.

**Comment by writerly03** [comment]
> If you PR into the staging branch and merged it will show up on https://staging.hypha.coop/ that way anyone can review the content without deploying locally.

I don't know how to PR into the staging branch though

**Pull request merged**
