### PR TITLE
Add listening at scale post

### LINKED ISSUE #441: Publish MARCH Dripline post: Listening at scale with Polis
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
🗣 **Loomio:** N/A  
📅 **Due date:** N/A  
🎯 **Success criteria:** Post is published on Dripline

...

## Todo

- [x] brainstorm
- [x] interview. [notes](https://meetings.hypha.coop/2021-02-11-business-planning.html)
- [x] first draft. [gdoc](https://docs.google.com/document/d/1Otvfq0VIJfqevsq5SisB7-uovEDL18CXLwXrzqggl7k/edit#)
- [x] review.
  - [x] dc added some content, revised + left comments 
  - [x] uv  
- [x] edits
  - [x] dc
  - [x] uv
- [x] final version -- pc
- [x] create dripline pull request -- dc
- [x] make GIFs -- pc
- [x] publish - ~~April 20ish~~ Apr 30
- [x] tweet & share -- pc

### PR DESCRIPTION
**Pull request by dcwalk**
Resolves: https://github.com/hyphacoop/organizing/issues/441

Post pre-flight:

- [x] add text
   - [x] handle text colours 
- [x] add images
   - [x] add alt text 
- [x] choose title
- [x] choose tagline
- [x] review on staging
- [x] publish to prod ~May 4~ May 5 https://github.com/hyphacoop/hypha.coop/pull/33

### CODE REVIEW

**Comment by patcon** [comment]
Thanks dc! Was this intentionally skipping `staging`? (I think it's ok to go straight to master!)

**Comment by dcwalk** [comment]
Changed to be on staging branch, tho `https://staging.hypha.coop/` is not resolving for me.

**Comment by dcwalk** [comment]
@patcon can you land this? I am not well positioned/current on discussions on deploy process

**Comment by patcon** [comment]
sure @dcwalk 🙌 

@hyphacoop/infrastructure-wg any idea why this wouldn't be deploying to staging rn? I'm seeing that the hostname isn't found: https://travis-ci.com/github/hyphacoop/hypha.coop/builds/224980122#L807

**Pull request merged**
